version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  create-pdf:
    lang: golang-middleware
    handler: ./create-pdf
    image: alexellis/create-pdf:0.2.0
    build_args:
      GO111MODULE: on
